# Generated by Django 5.2 on 2025-04-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_bonuses_bonustransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonustransaction',
            options={'permissions': [('can_redeem_bonus', 'Can redeem bonus orders')]},
        ),
    ]
