# Generated by Django 5.2 on 2025-04-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dietary_type',
            field=models.CharField(blank=True, choices=[('pescatarian', 'Pescatarian'), ('no_meat', 'No Meat'), ('gluten_free', 'Gluten-Free')], max_length=50, null=True),
        ),
    ]
