# Generated by Django 5.2 on 2025-04-22 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_dietaryoption_remove_dish_dietary_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietaryoption',
            options={'verbose_name': 'Dietary Option', 'verbose_name_plural': 'Dietary Options'},
        ),
        migrations.RemoveField(
            model_name='dish',
            name='dietary_types',
        ),
        migrations.AddField(
            model_name='dish',
            name='dietary_types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.dietaryoption'),
            preserve_default=False,
        ),
    ]
