# Generated by Django 5.2 on 2025-04-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_dietaryoption_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dietary_types',
        ),
        migrations.AddField(
            model_name='dish',
            name='dietary_types',
            field=models.ManyToManyField(to='restaurant.dietaryoption'),
        ),
    ]
