name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker compose build

      - name: Run Django & DB Containers
        run: docker compose up -d db web

      - name: Run Django Tests
        run: docker compose exec -T web python manage.py test --parallel 1

      - name: Shutdown Containers
        if: ${{ always() }}
        run: docker compose down -v
