name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker compose build

      - name: Run Django Container
        run: docker compose up -d

      - name: Run Django Tests
        run: docker compose run web python manage.py test

      - name: Shutdown Containers
        run: docker compose down
