name: lab-3 dockerfile compose & build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker compose build

      - name: Write .env for compose
        run: |
          cat <<EOF > .env
          DB_NAME=${{ env.DB_NAME }}
          DB_USER=${{ env.DB_USER }}
          DB_PASSWORD=${{ env.DB_PASSWORD }}
          EOF

      - name: Run Django & DB Containers
        run: docker compose up -d db web

      - name: Run Django Tests
        run: docker compose exec -T web python manage.py test --parallel 1

      - name: Shutdown Containers
        if: ${{ always() }}
        run: docker compose down -v
