name: build-and-deploy-to-render

on:
  push:
    branches: [main, master]
  workflow_dispatch:

env:
  python_version: "3.11"

  DB_NAME:     ${{ secrets.DB_NAME }}
  DB_USER:     ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST:     ${{ secrets.DB_HOST }}
  DB_PORT:     ${{ secrets.DB_PORT }}

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up python ${{ env.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run django migrations
        run: python manage.py migrate --noinput

      - name: run tests
        run: python manage.py test

  deploy-render:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: trigger render deploy-hook
        env:
          render_deploy_hook_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$render_deploy_hook_url" ]; then
            echo "RENDER_DEPLOY_HOOK_URL is not set"; exit 1;
          fi
          curl -fsSL "$render_deploy_hook_url"
